<a href="https://colab.research.google.com/github/whuera/procesamiento-datos/blob/master/m3_t1_ventas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [ ]:
indice = ["Juan", "Camila", "Daniel", "Luis", "Juan", "Ana", "Camila", "Ana","Luis", "Juan", "Ana", "Juan"]

In [ ]:
dicc_datos = {
    0:"Juan",
    1:"Camila",
    2:"Daniel",
    3:"Luis",
    4:"Juan",
    5:"Ana",
    6:"Camila",
    7:"Ana",
    8:"Luis",
    9:"Juan",
    10:"Ana",
    11:"Juan"
}

In [ ]:
ventas_2021 = pd.Series([100,200,110,90,150,80,70,100,100,110,90,100],
                        index=indice)
ventas_2021

Juan      100
Camila    200
Daniel    110
Luis       90
Juan      150
Ana        80
Camila     70
Ana       100
Luis      100
Juan      110
Ana        90
Juan      100
dtype: int64

In [ ]:
dicc_datos = {
    0:"Juan",
    1:"Camila",
    2:"Daniel",
    3:"Luis",
    4:"Juan",
    5:"Ana",
    6:"Camila",
    7:"Ana",
    8:"Luis",
    9:"Juan",
    10:"Ana",
    11:"Juan"
}

In [ ]:
ventas_2021 = pd.Series(dicc_datos)
ventas_2021

0       Juan
1     Camila
2     Daniel
3       Luis
4       Juan
5        Ana
6     Camila
7        Ana
8       Luis
9       Juan
10       Ana
11      Juan
dtype: object

In [ ]:
resultado_ventas_2021 = pd.DataFrame({"Clientes": dicc_datos})
resultado_ventas_2021

   Clientes
0      Juan
1    Camila
2    Daniel
3      Luis
4      Juan
5       Ana
6    Camila
7       Ana
8      Luis
9      Juan
10      Ana
11     Juan

In [ ]:
ventas_por_cliente = pd.Series([100,200,110,90,150,80,70,100,100,110,90,100],
                               index = [0,1,2,3,4,5,6,7,8,9,10,11])

In [ ]:
resultado_ventas_2021 = pd.DataFrame({"Clientes": dicc_datos, "Ventas":ventas_por_cliente})
resultado_ventas_2021

   Clientes  Ventas
0      Juan     100
1    Camila     200
2    Daniel     110
3      Luis      90
4      Juan     150
5       Ana      80
6    Camila      70
7       Ana     100
8      Luis     100
9      Juan     110
10      Ana      90
11     Juan     100

In [22]:
ventas_clientes_2021 = pd.Series([100.0,200.0,"110,00",90.0,150.0,80.0,70.0,100.0,100.0,110.0,90.0,"100,00"])
ventas_clientes_2021
Clientes_2021 = pd.Series(["JUan","camila","DanIel","Luis","Juan","Ana","Camila","Ana","LuiS","Juan","Ana","Juan"])
Clientes_2021
df1 = pd.DataFrame(ventas_clientes_2021, columns=["Ventas"])
df2 = pd.DataFrame(Clientes_2021, columns=["Clientes"])
df3 = pd.concat([df2,df1], axis = 1)
df3
df3.sort_values(by=['Clientes'], ascending = True)

   Clientes  Ventas
5       Ana    80.0
7       Ana   100.0
10      Ana    90.0
6    Camila    70.0
2    DanIel  110,00
0      JUan   100.0
4      Juan   150.0
9      Juan   110.0
11     Juan  100,00
8      LuiS   100.0
3      Luis    90.0
1    camila   200.0

In [23]:
ventas_clientes_2021 = pd.Series([100.0,200.0,"110,00",90.0,150.0,80.0,70.0,100.0,100.0,110.0,90.0,"100,00"])
ventas_clientes_2021

0      100.0
1      200.0
2     110,00
3       90.0
4      150.0
5       80.0
6       70.0
7      100.0
8      100.0
9      110.0
10      90.0
11    100,00
dtype: object

**Generar los dataframe con datos**

In [24]:
ventas_clientes_2021 = pd.Series([100.0,200.0,110.00,90.0,150.0,80.0,70.0,100.0,100.0,110.0,90.0,110.00])
ventas_clientes_2021
Clientes_2021 = pd.Series(["Juan","Camila","Daniel","Luis","Juan","Ana","Camila","Ana","Luis","Juan","Ana","Juan"])
Clientes_2021
df1 = pd.DataFrame(ventas_clientes_2021, columns=["Ventas"])
df2 = pd.DataFrame(Clientes_2021, columns=["Clientes"])
df3 = pd.concat([df2,df1], axis = 1)
df3
df3.sort_values(by=['Clientes'], ascending = True)

   Clientes  Ventas
5       Ana    80.0
7       Ana   100.0
10      Ana    90.0
1    Camila   200.0
6    Camila    70.0
2    Daniel   110.0
0      Juan   100.0
4      Juan   150.0
9      Juan   110.0
11     Juan   110.0
3      Luis    90.0
8      Luis   100.0

**Agrupar por Producto y Vendedor y sumar las ventas**

In [83]:
ventas_por_grupo = df3.groupby(['Clientes','Ventas'])['Ventas'].sum()
ventas_por_grupo

Clientes  Ventas
Ana       80.0       80.0
          90.0       90.0
          100.0     100.0
Camila    70.0       70.0
          200.0     200.0
Daniel    110.0     110.0
Juan      100.0     100.0
          110.0     220.0
          150.0     150.0
Luis      90.0       90.0
          100.0     100.0
Name: Ventas, dtype: float64

**Ordenar y Agrupar Datos**

In [91]:
Clientes_2021 = pd.Series(["JUan","camila","DanIel","Luis","Juan","Ana","Camila","Ana","LuiS","Juan","Ana","Juan"])
Clientes_2021 = Clientes_2021.str.upper()
Clientes_2021 = Clientes_2021.str.capitalize()
df1 = pd.DataFrame(ventas_clientes_2021, columns=["Ventas"])
df2 = pd.DataFrame(Clientes_2021, columns=["Clientes"])
df3 = pd.concat([df2,df1], axis = 1)
df3
df3.sort_values(by=['Clientes'], ascending = True)
ventas_por_grupo1 = df3.groupby(['Clientes','Ventas'], as_index=False).agg({'Ventas': 'sum'})
ventas_por_grupo1
ventas_por_grupo1.groupby(['Clientes','Ventas']).agg(total=('Ventas', min))
ventas_por_grupo1

   Clientes  Ventas
0       Ana    80.0
1       Ana    90.0
2       Ana   100.0
3    Camila    70.0
4    Camila   200.0
5    Daniel   110.0
6      Juan   100.0
7      Juan   220.0
8      Juan   150.0
9      Luis    90.0
10     Luis   100.0

**Ordenar y procesar datos**

In [72]:
compute_ventas = ventas_por_grupo1.pivot_table("Ventas", index = "Clientes", aggfunc = {"Ventas": ["count", sum, "mean"]})
df_compute = pd.DataFrame(compute_ventas)
df_compute

          count        mean    sum
Clientes
Ana           3   90.000000  270.0
Camila        2  135.000000  270.0
Daniel        1  110.000000  110.0
Juan          3  156.666667  470.0
Luis          2   95.000000  190.0

**Obtener la diferencia de ventas**

In [81]:
valor_max = df_compute.max()
valor_max
valor_min = df_compute.min()
valor_min
val_dif = valor_max - valor_min
val_dif

count      2.000000
mean      66.666667
sum      360.000000
dtype: float64

**Promedio Ventas**

In [86]:
ventas_por_grupo = df3.groupby(['Clientes','Ventas'])['Ventas'].sum()
ventas_por_grupo

Clientes  Ventas
Ana       80.0       80.0
          90.0       90.0
          100.0     100.0
Camila    70.0       70.0
          200.0     200.0
Daniel    110.0     110.0
Juan      100.0     100.0
          110.0     220.0
          150.0     150.0
Luis      90.0       90.0
          100.0     100.0
Name: Ventas, dtype: float64

In [88]:
compute_ventas = ventas_por_grupo1.pivot_table("Ventas", index = "Clientes", aggfunc = {"Ventas": ["count", sum, "mean"]})
df_compute = pd.DataFrame(compute_ventas)
df_compute

          count        mean    sum
Clientes
Ana           3   90.000000  270.0
Camila        2  135.000000  270.0
Daniel        1  110.000000  110.0
Juan          3  156.666667  470.0
Luis          2   95.000000  190.0

**promedio de compras**

In [97]:
df3.groupby("Clientes").mean()
df3.groupby("Clientes").last()

          Ventas
Clientes
Ana         90.0
Camila      70.0
Daniel     110.0
Juan       110.0
Luis       100.0

**Resultado**

In [95]:
df3.groupby("Clientes").mean() - df3.groupby("Clientes").last()

          Ventas
Clientes
Ana          0.0
Camila      65.0
Daniel       0.0
Juan         7.5
Luis        -5.0

import numpy as np
from google.colab import autoviz
df_6377571352053172770 = autoviz.get_df('df_6377571352053172770')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_6377571352053172770, *['Ventas'], **{})
chart

import numpy as np
from google.colab import autoviz
df_6377571352053172770 = autoviz.get_df('df_6377571352053172770')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_6377571352053172770, *['Ventas'], **{})
chart